services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sampledb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network
    restart: always

  spring-boot-app:
    image: openjdk:17-jdk-alpine
    container_name: spring-boot-app
    volumes:
      - ./target/devInv-0.0.1-SNAPSHOT.jar:/app/devInv-0.0.1-SNAPSHOT.jar
    working_dir: /app
    command: ["java", "-jar", "devInv-0.0.1-SNAPSHOT.jar"]
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/sampledb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - my-network
    restart: always

volumes:
  mysql-data:

networks:
  my-network:
